services:
  ntfy:
    #image: binwiederhier/ntfy:v2.11.0
    image: binwiederhier/ntfy:v2.24.0
    environment:
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db 
    #   NTFY_AUTH_DEFAULT_ACCESS: deny-all
    restart: always
    volumes:
      - ./db:/var/lib/ntfy/
    #  - ./ntfy/etc/:/etc/ntfy/
    #  - ./ntfy/cache/:/var/cache/ntfy/
    ports:
      - 80:80
    command: serve
    stdin_open: true
    tty: true